apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitops-demo.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitops-demo.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "gitops-demo.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
