apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitops-demo.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitops-demo.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "gitops-demo.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
