apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-demo.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "gitops-demo.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: ClusterIP
