frontend:
  replicaCount: 2
  image:
    repository: 322686612450.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo-frontend
    tag: "latest"
  containerPort: 8080
  service:
    port: 80

backend:
  replicaCount: 2
  image:
    repository: 322686612450.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo-backend
    tag: "latest"
  containerPort: 8000
  service:
    port: 8000
