frontend:
  replicaCount: 2
  image:
    repository: YOUR_ECR_REGISTRY/gitops-demo-frontend
    tag: "REPLACE_ME"
  containerPort: 8080
  service:
    port: 80

backend:
  replicaCount: 2
  image:
    repository: YOUR_ECR_REGISTRY/gitops-demo-backend
    tag: "REPLACE_ME"
  containerPort: 8000
  service:
    port: 8000
