apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo
  namespace: argocd
spec:
  project: gitops-demo
  source:
    repoURL: https://github.com/suren00-77-99/Argo-CD.git
    targetRevision: main
    path: helm/gitops-demo
    helm:
      valueFiles:
        - ../../environments/dev/frontend-values.yaml
        - ../../environments/dev/backend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
